export const estouAquiFlow = [
    {
        id: 'reason',
        question: 'Qual foi o motivo da sua visita hoje?',
        type: 'single-select',
        options: [
            'Consulta',
            'Emergência leve',
            'Vacinação',
            'Buscar medicação',
            'Exame',
            'Outro',
        ],
    },
    {
        id: 'status',
        question: 'Você já foi atendido?',
        type: 'single-select',
        options: ['Sim', 'Ainda estou esperando', 'Desisti'],
    },
    {
        id: 'wait_duration_attended',
        showIf: { status: 'Sim' },
        question: 'Quanto tempo levou para você ser atendido?',
        type: 'single-select',
        options: [
            'Menos de 10min',
            '10–30min',
            '30–60min',
            '1–2h',
            '2–3h',
            '+3h',
        ],
    },
    {
        id: 'wait_duration_waiting',
        showIf: { status: 'Ainda estou esperando' },
        question: 'Quanto tempo você já está esperando?',
        type: 'single-select',
        options: [
            'Menos de 10min',
            '10–30min',
            '30–60min',
            '1–2h',
            '2–3h',
            '+3h',
        ],
    },
    {
        id: 'quit_reason',
        showIf: { status: 'Desisti' },
        question: 'Por que você desistiu?',
        type: 'single-select',
        options: [
            'Demora',
            'Faltava profissional',
            'Lotação',
            'Não tinha vagas',
            'Outro',
        ],
    },
    {
        id: 'service_received',
        showIf: { status: 'Sim' },
        question: 'Você conseguiu o serviço que procurava?',
        type: 'single-select',
        options: ['Sim', 'Parcialmente', 'Não'],
    },
    {
        id: 'professional_available',
        showIf: { status: 'Sim' },
        question: 'Havia profissional disponível?',
        type: 'single-select',
        options: ['Sim', 'Não'],
    },
    {
        id: 'service_rating',
        showIf: { status: 'Sim' },
        question: 'Como você avaliaria a qualidade do atendimento?',
        type: 'rating',
        scale: 5,
    },
    {
        id: 'medication',
        showIf: { status: 'Sim' },
        question: 'Você conseguiu a medicação que precisava?',
        type: 'single-select',
        options: ['Sim', 'Não', 'Não precisei'],
    },
    {
        id: 'issue_resolved',
        showIf: { status: 'Sim' },
        question: 'Seu problema foi resolvido?',
        type: 'single-select',
        options: ['Sim', 'Parcialmente', 'Não'],
    },
    {
        id: 'general_experience',
        question: 'Como você descreveria sua experiência hoje?',
        type: 'single-select',
        options: ['Excelente', 'Boa', 'Ok', 'Ruim', 'Péssima'],
    },
    {
        id: 'comment',
        question: 'Algum comentário que possa ajudar outras pessoas?',
        type: 'text',
        optional: true,
    },
]
